import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  Bell,
  BookMarked,
  Bot,
  Boxes,
  Building2,
  CalendarClock,
  CalendarSync,
  ChartNoAxesColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleStop,
  CircleX,
  Clock,
  Columns3,
  Command,
  Copy,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Factory,
  FileText,
  Filter,
  Gauge,
  GripVertical,
  History,
  Image,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  Link2,
  ListChecks,
  Lock,
  LogOut,
  MapPinX,
  MessageSquare,
  Minus,
  OctagonAlert,
  PackageMinus,
  PackagePlus,
  PackageX,
  PanelLeft,
  PanelLeftClose,
  PanelRight,
  Paperclip,
  Play,
  PlugZap,
  Plus,
  RefreshCw,
  Reply,
  Rows3,
  ScrollText,
  Search,
  SearchX,
  Send,
  Settings2,
  Sheet,
  ShieldCheck,
  Sparkles,
  SquarePen,
  StickyNote,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  TruckElectric,
  Undo2,
  Upload,
  UserCog,
  UserPlus,
  Users,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/src/lib/cn";

/**
 * Explicit registry rather than a dynamic namespace lookup. Keeps tree-shaking
 * intact while still letting config files reference icons by string name.
 */
export const ICONS = {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  Bell,
  BookMarked,
  Bot,
  Boxes,
  Building2,
  CalendarClock,
  CalendarSync,
  ChartNoAxesColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleStop,
  CircleX,
  Clock,
  Columns3,
  Command,
  Copy,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Factory,
  FileText,
  Filter,
  Gauge,
  GripVertical,
  History,
  Image,
  Inbox,
  Info,
  Layers,
  LayoutDashboard,
  Link2,
  ListChecks,
  Lock,
  LogOut,
  MapPinX,
  MessageSquare,
  Minus,
  OctagonAlert,
  PackageMinus,
  PackagePlus,
  PackageX,
  PanelLeft,
  PanelLeftClose,
  PanelRight,
  Paperclip,
  Play,
  PlugZap,
  Plus,
  RefreshCw,
  Reply,
  Rows3,
  ScrollText,
  Search,
  SearchX,
  Send,
  Settings2,
  Sheet,
  ShieldCheck,
  Sparkles,
  SquarePen,
  StickyNote,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  TruckElectric,
  Undo2,
  Upload,
  UserCog,
  UserPlus,
  Users,
  X,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

const SIZE_CLASS = {
  xs: "size-3",
  sm: "size-3.5",
  md: "size-4",
  lg: "size-5",
  xl: "size-6",
} as const;

export interface IconProps {
  name: string;
  size?: keyof typeof SIZE_CLASS;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = "md", className, strokeWidth = 1.75 }: IconProps) {
  const Resolved = ICONS[name as IconName] ?? CircleHelp;
  return (
    <Resolved
      className={cn(SIZE_CLASS[size], "shrink-0", className)}
      strokeWidth={strokeWidth}
      aria-hidden="true"
    />
  );
}
